import { ContentDetector } from './content-detector';
import { ContentExtractor } from './content-extractor';
import { ElementPicker } from './element-picker';
import { ScrollController } from './scroll-controller';
import { OverlayApp } from './overlay-app';
import { KeyboardInputController } from '../input/keyboard-input-controller';
import { SettingsStore } from '../settings/settings-store';
import type { Settings } from '../settings/settings-types';
import { Tokenizer, comparableText } from '../typing/tokenizer';
import { TypingEngine } from '../typing/typing-engine';
import { WpmTracker } from '../typing/wpm-tracker';
import { createSessionSummary } from '../typing/session-stats';
import type { TextBlock, WordToken } from '../typing/types';

type AppState='inactive'|'detecting'|'selectionPreview'|'pickingElement'|'ready'|'typing'|'idle'|'paused'|'completed'|'error';
export class AppController {
  private state:AppState='inactive';private settings!:Settings;private overlay:OverlayApp|null=null;private input:KeyboardInputController|null=null;private engine:TypingEngine|null=null;private tracker:WpmTracker|null=null;private blocks:TextBlock[]=[];private tokens:WordToken[]=[];private source:HTMLElement|null=null;private timer:number|null=null;private startedAt=0;private originalOutline='';
  private readonly detector=new ContentDetector();private readonly extractor=new ContentExtractor();private readonly picker=new ElementPicker();private readonly tokenizer=new Tokenizer();private readonly scroller=new ScrollController();private readonly store=new SettingsStore();
  async activate():Promise<void>{if(this.state!=='inactive'){this.close();return}this.state='detecting';this.settings=await this.store.load();this.overlay=new OverlayApp(this.settings,{start:()=>this.start(),pick:()=>void this.pick(),detect:()=>this.detect(),restart:()=>this.restart(),close:()=>this.close(),saveSettings:(s)=>void this.saveSettings(s)});this.detect()}
  close():void{this.clearSourceHighlight();this.picker.cleanup();this.stopSession();this.overlay?.destroy();this.overlay=null;this.state='inactive'}
  private detect():void{this.state='detecting';this.overlay?.setVisible(true);const result=this.detector.detect();if(!result.element||result.confidence==='none'){void this.pick();return}this.selectSource(result.element);this.state='selectionPreview';this.highlightSource();this.overlay?.preview(result.wordCount,result.confidence)}
  private async pick():Promise<void>{this.clearSourceHighlight();this.stopSession();this.state='pickingElement';this.overlay?.setVisible(false);const element=await this.picker.pick();this.overlay?.setVisible(true);if(!element){this.detect();return}this.selectSource(element);if(!this.tokens.length){this.overlay?.announce('The selected element does not contain usable text.');this.detect();return}this.start()}
  private selectSource(element:HTMLElement):void{this.source=element;this.blocks=this.extractor.extract(element);this.tokens=this.tokenizer.tokenize(this.blocks,{skipEmojis:this.settings.skipEmojis,skipPunctuation:this.settings.skipPunctuation})}
  private start():void{if(!this.tokens.length){void this.pick();return}this.clearSourceHighlight();this.stopSession();this.state='ready';this.engine=new TypingEngine(this.tokens,this.typingOptions());this.tracker=new WpmTracker(this.settings.segmentWords,this.settings.idleSeconds*1000);this.startedAt=Date.now();this.overlay?.showTyping(this.tokens,this.blocks,this.engine);this.input=new KeyboardInputController({text:(value)=>this.typeText(value),space:()=>this.completeWord(),backspace:(whole)=>this.backspace(whole),escape:()=>this.escape(),activity:()=>this.input?.focus(),capsLock:(active)=>this.overlay?.setCapsLock(active)});if(this.overlay){const shadow=this.overlay.host.shadowRoot;shadow?.append(this.input.input);shadow?.querySelector('.reader')?.addEventListener('pointerdown',()=>this.input?.focus())}this.input.focus();this.timer=window.setInterval(()=>this.tick(),200);this.tick()}
  private typeText(value:string):void{if(!this.engine||!this.tracker||this.state==='paused'||this.state==='completed')return;this.state='typing';const now=performance.now();for(const result of this.engine.type(value)){if(result.accepted)this.tracker.recordKeystroke(Boolean(result.correct),now)}this.render();const snapshot=this.engine.getSnapshot();const target=this.engine.getToken().text;const typed=snapshot.words[snapshot.currentIndex]!.typed;if(snapshot.currentIndex===this.tokens.length-1&&comparableText(typed,this.typingOptions())===comparableText(target,this.typingOptions()))this.completeWord()}
  private completeWord():void{if(!this.engine||!this.tracker||this.state==='paused'||this.state==='completed')return;const before=this.engine.getSnapshot();const token=this.engine.getToken();const result=this.engine.completeWord();if(!result.accepted)return;const now=performance.now();if(before.words[before.currentIndex]!.typed==='')this.tracker.recordSkippedCharacters([...token.text].length,now);const segment=this.tracker.completeWord(now);if(segment)this.overlay?.announce(`Segment completed: ${segment.wpm.toFixed(0)} WPM.`);if(result.sessionCompleted){this.tracker.finishPartialSegment(now);this.state='completed';this.input?.setActive(false);const summary=createSessionSummary(this.engine.getSnapshot().metrics,this.tracker.getSnapshot(now),this.startedAt);this.overlay?.showResults(summary)}else this.render()}
  private backspace(whole:boolean):void{if(!this.engine||this.state==='paused'||this.state==='completed')return;this.engine.backspace(whole);this.render()}
  private escape():void{if(this.state==='paused'){this.close();return}if(this.state==='typing'||this.state==='idle'||this.state==='ready'){this.state='paused';this.tracker?.pause(performance.now());this.input?.setActive(false);this.overlay?.announce('Paused. Press Escape again to exit, or click the text to continue.');this.overlay?.host.shadowRoot?.addEventListener('click',()=>this.resume(),{once:true})}}
  private resume():void{if(this.state!=='paused')return;this.state='typing';this.input?.setActive(true);this.overlay?.announce('Typing resumed.')}
  private render():void{if(!this.engine)return;const current=this.overlay?.updateTyping(this.engine);if(current&&this.overlay?.host.shadowRoot){const reader=this.overlay.host.shadowRoot.querySelector<HTMLElement>('.reader');if(reader)this.scroller.keepVisible(current,reader)}}
  private tick():void{if(!this.tracker||this.state==='paused'||this.state==='completed')return;const snapshot=this.tracker.getSnapshot(performance.now());if(snapshot.status==='idle'&&this.state==='typing')this.state='idle';else if(snapshot.status==='typing'&&this.state==='idle')this.state='typing';this.overlay?.updateStats(snapshot)}
  private restart():void{this.start()}
  private async saveSettings(settings:Settings):Promise<void>{const tokenizationChanged=this.settings.skipEmojis!==settings.skipEmojis||this.settings.skipPunctuation!==settings.skipPunctuation;this.settings=settings;await this.store.save(settings);this.overlay?.updateSettings(settings);if(tokenizationChanged){this.tokens=this.tokenizer.tokenize(this.blocks,{skipEmojis:settings.skipEmojis,skipPunctuation:settings.skipPunctuation});this.start();return}this.engine?.updateOptions(this.typingOptions());this.tracker?.setSegmentSize(settings.segmentWords);this.tracker?.setIdleLimit(settings.idleSeconds);this.render();this.input?.focus()}
  private stopSession():void{if(this.timer!==null){clearInterval(this.timer);this.timer=null}this.input?.destroy();this.input=null;this.engine=null;this.tracker=null}
  private typingOptions(){return{caseSensitive:this.settings.caseSensitive,skipPunctuation:this.settings.skipPunctuation}}
  private highlightSource():void{if(!this.source)return;this.originalOutline=this.source.style.outline;this.source.style.outline='3px solid #9b87ff';this.source.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
  private clearSourceHighlight():void{if(this.source)this.source.style.outline=this.originalOutline}
}
